### ISSUE TITLE
Conversion from |Z| and theta to Z' and Z'' is wrong

### ISSUE THREAD

**Issue by r-mouta** [levi-ufma/SmartOutput#4]
The theta values in the csv input are in degrees, but the functions numpy.sin( ) and numpy.cos( ) assume that the values are in radians. Thus, theta must be converted into radians first. The code should be 
```
z_re = matriz[:, 1]*np.cos(np.radians(matriz[:, 2]))
z_im = matriz[:, 1]*np.sin(np.radians(matriz[:, 2]))
```
 instead of
```
z_re = matriz[:, 1]*np.cos(matriz[:, 2])
z_im = matriz[:, 1]*np.sin(matriz[:, 2]) 
```

**Comment by jherfson** [comment]
Change of expression made.
